import React, { useEffect } from 'react';
import { ArrowLeft, Shield, AlertTriangle } from 'lucide-react';

export const TermsOfService = ({ onBack }) => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="min-h-screen bg-white text-slate-800 font-sans">
      {/* Header */}
      <div className="bg-slate-950 py-6 border-b border-slate-900 sticky top-0 z-50">
        <div className="container mx-auto px-6 flex justify-between items-center">
          <div className="flex items-center gap-2 text-white font-bold text-xl">
            <Shield className="w-8 h-8 text-amber-500" />
            <span>Marketing<span className="text-amber-500">Master</span></span>
          </div>
          <button 
            onClick={onBack}
            className="flex items-center gap-2 text-slate-300 hover:text-white transition-colors text-sm font-medium"
          >
            <ArrowLeft className="w-4 h-4" /> Back to Home
          </button>
        </div>
      </div>

      <div className="container mx-auto px-6 py-16 max-w-4xl">
        <h1 className="text-4xl font-bold text-slate-900 mb-2">Terms of Service</h1>
        <p className="text-slate-500 mb-12">Last Updated: October 26, 2024</p>

        <div className="bg-amber-50 border border-amber-200 p-6 rounded-xl mb-12 flex gap-4">
          <AlertTriangle className="w-6 h-6 text-amber-600 flex-shrink-0" />
          <div className="text-sm text-amber-900 leading-relaxed">
            <strong>Important Notice:</strong> These terms include an agreement to resolve disputes by arbitration on an individual basis and a waiver of class action rights. By using this site, you acknowledge and agree to these provisions.
          </div>
        </div>

        <div className="prose prose-slate max-w-none space-y-8">
          <section>
            <h2 className="text-2xl font-bold text-slate-900 mb-4">1. Acceptance of Terms</h2>
            <p className="leading-relaxed">
              By accessing and using this website (the "Site") operated by MarketingMaster/7XCRM ("Company," "we," or "us"), you accept and agree to be bound by the terms and provision of this agreement. In addition, when using these particular services, you shall be subject to any posted guidelines or rules applicable to such services.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 mb-4">2. Description of Services</h2>
            <p className="leading-relaxed">
              MarketingMaster provides digital marketing consulting, lead generation strategies, and educational content related to the Life Insurance industry (specifically IUL, Term Life, and Annuities). The content provided is for informational purposes only and does not constitute financial, legal, or insurance advice.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 mb-4">3. TCPA Consent & Communications</h2>
            <p className="leading-relaxed mb-4">
              By submitting your contact information (name, email, phone number) on our forms, you expressly consent to receive communications from us, including but not limited to:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Telephone calls, including prerecorded messages and artificial voice messages.</li>
              <li>Text messages (SMS/MMS) regarding our services, strategy sessions, and updates.</li>
              <li>Emails containing marketing materials and educational content.</li>
            </ul>
            <p className="mt-4 leading-relaxed">
              You agree that we may contact you at the telephone number(s) you provide, even if your number is listed on a corporate, state, or federal Do-Not-Call registry. Consent is not a condition of purchase. Standard message and data rates may apply. You may opt-out of SMS communications at any time by replying "STOP".
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 mb-4">4. No Guarantee of Results</h2>
            <p className="leading-relaxed">
              While we share case studies and testimonials regarding revenue generated by our strategies (e.g., "$7M+ Annual Revenue"), these are specific examples and do not guarantee that you or your agency will achieve the same results. Marketing success depends on numerous factors including your location, budget, sales ability, and market conditions. All services are provided "As Is" without warranty of any kind regarding specific financial outcomes.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 mb-4">5. Intellectual Property</h2>
            <p className="leading-relaxed">
              The Site and its original content, features, and functionality are owned by MarketingMaster/7XCRM and are protected by United States and international copyright, trademark, patent, trade secret, and other intellectual property or proprietary rights laws. You agree not to reproduce, duplicate, copy, sell, resell or exploit any portion of the Service without express written permission by us.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 mb-4">6. Limitation of Liability</h2>
            <p className="leading-relaxed">
              In no event shall MarketingMaster, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from (i) your access to or use of or inability to access or use the Service; (ii) any conduct or content of any third party on the Service; (iii) any content obtained from the Service; and (iv) unauthorized access, use or alteration of your transmissions or content.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 mb-4">7. Governing Law</h2>
            <p className="leading-relaxed">
              These Terms shall be governed and construed in accordance with the laws of the State of Georgia, United States, without regard to its conflict of law provisions. Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 mb-4">8. Contact Us</h2>
            <p className="mb-4">If you have any questions about these Terms, please contact us:</p>
            <div className="bg-slate-50 p-6 rounded-lg border border-slate-200">
              <p className="font-bold">MarketingMaster / 7XCRM</p>
              <p>1424 N Brown Rd #450</p>
              <p>Lawrenceville, GA 30043</p>
              <p>Email: Assistant@7xcrm.com</p>
            </div>
          </section>
        </div>
      </div>
    </div>
  );
};